### ISSUE TITLE
`analyzeRepositoriesFromLocalFilesystem` results in "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by dalvizu** [atomist-blogs/org-visualizer#260]
I am receiving this error running [org-visualizer](https://github.com/atomist/org-visualizer) and this command:

```
/home/node/.npm-global/bin/atomist analyze local repositories --localDirectory=/root/atomist/projects/
```

I have a cron job running this command every 5m on a docker container. Eventually (I don't have an exact timeframe, but greater than two weeks and probably greater than a month), the cron job starts failing. Inspecting docker logs of the org-visualizer container reveals this error:

```
2020-06-10T18:20:03.340Z [m:16:92ad7166-f3bd-4119-bf74-f8108436b7b0:ping-atomist-d7mgz:analyzeRepositoriesFromLocalFilesystem:001] [debug] Incoming command invocation '{"command":"analyzeRepositoriesFromLocalFilesystem","parameters":[{"name":"github://user_token?scopes=repo,user:email,read:user","value":"not.a.real.token"},{"name":"_","value":["analyze","local","repositories"]},{"name":"localDirectory","value":"/root/atomist/projects/"},{"name":"local.directory","value":"/root/atomist/projects/"},{"name":"$0","value":"/home/node/.npm-global/bin/atomist"}],"mapped_parameters":[{"name":"slackTeam","value":"local"},{"name":"github://user_token?scopes=repo,user:email,read:user","value":"not.a.real.token"},{"name":"_","value":["analyze","local","repositories"]},{"name":"localDirectory","value":"/root/atomist/projects/"},{"name":"local.directory","value":"/root/atomist/projects/"},{"name":"$0","value":"/home/node/.npm-global/bin/atomist"}],"secrets":[{"uri":"github://user_token?scopes=repo,user:email,read:user","value":"n**************n"}],"correlation_id":"atomist-cli-10000-general-1591813203334","api_version":"1","team":{"id":"local","name":"ping-atomist-d7mgz"}}'
2020-06-10T18:20:03.340Z [m:16:92ad7166-f3bd-4119-bf74-f8108436b7b0:ping-atomist-d7mgz:analyzeRepositoriesFromLocalFilesystem:001] [info ] Invoking command handler 'analyzeRepositoriesFromLocalFilesystem'
2020-06-10T18:20:03.433Z [m:16:92ad7166-f3bd-4119-bf74-f8108436b7b0:ping-atomist-d7mgz:analyzeRepositoriesFromLocalFilesystem:094] [error] Maximum call stack size exceeded
2020-06-10T18:20:03.446Z [m:16:92ad7166-f3bd-4119-bf74-f8108436b7b0:ping-atomist-d7mgz:analyzeRepositoriesFromLocalFilesystem:107] [error] Failed invocation of command 'analyzeRepositoriesFromLocalFilesystem': Maximum call stack size exceeded
2020-06-10T18:20:03.447Z [m:16:92ad7166-f3bd-4119-bf74-f8108436b7b0:ping-atomist-d7mgz:analyzeRepositoriesFromLocalFilesystem:108] [error] RangeError: Maximum call stack size exceeded
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:544:25)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
    at c.paramsMaker (/sdm/node_modules/@atomist/sdm/lib/api-helper/machine/handlerRegistrations.ts:545:60)
```

David Dooling identified (on Slack) that "It seems to be complaining about this line":

https://github.com/atomist/sdm/blob/1.7.0/lib/api-helper/machine/handlerRegistrations.ts#L545

"Specifically when trying to call the function returned by toFactory(oldMaker)"

*Environment*:
```
atomist --version
@atomist/cli 1.8.0
@atomist/automation-client ^1.7.0
@atomist/sdm ^1.7.0
@atomist/sdm-core ^1.7.0
@atomist/sdm-local ^1.2.1
@atomist/sdm-pack-k8s ^1.10.0
```

Disk space is pretty free:

```
root@atomist-d7mgz:/sdm# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         194G   41G  153G  22% /
tmpfs            64M     0   64M   0% /dev
tmpfs            31G     0   31G   0% /sys/fs/cgroup
/dev/nvme0n1p1  194G   41G  153G  22% /etc/hosts
shm              64M  8.0K   64M   1% /dev/shm
/dev/nvme1n1    9.8G  494M  9.3G   5% /root/atomist/projects
tmpfs            31G   12K   31G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            31G     0   31G   0% /proc/acpi
tmpfs            31G     0   31G   0% /proc/scsi
tmpfs            31G     0   31G   0% /sys/firmware
```

*Resources*:

Slack convo: https://atomist-community.slack.com/archives/C29DMA0R4/p1591647122027200

**Comment by ddgenome** [comment]
Thank you for reporting this. Currently the only solution is to restart your container periodically. org-visualizer and this project have been deprecated.

**Comment by dalvizu** [comment]
I'm sorry reporting issues is an inconvenience to you. I'll make sure not to do that in the future.
